name = "Circuits"
uuid = "d2a218f5-c9f8-4bfd-b3ab-fe354e20ba05"
authors = ["David Gustavsson <david.e.gustavsson@gmail.com> and contributors"]
version = "0.1.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"

[compat]
Latexify = "0.14"
julia = "1"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
